# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
