# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 22:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171207_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog.Blog'),
            preserve_default=False,
        ),
    ]
